[phases.setup]
nixPkgs = ["dotnet-sdk"]

[phases.install]
cmds = ["dotnet restore"]

[phases.build]
cmds = ["dotnet publish --no-restore -c Release -o out"]

[start]
cmd = "cd out && dotnet SampeDemoApi.dll --urls http://0.0.0.0:$PORT"
